# -*- coding: utf-8 -*-
"""pythonProgramlamaDERS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5F-XA8KV022jrqZS4n4Rg3sb_eucM9p
"""

sinavNotu=int(input("Sınav Notunuzu Giriniz: "))

if (sinavNotu>100) or (sinavNotu<0):
  print("Yanlış Not girdiniz!!!")

elif (sinavNotu>=85) and (sinavNotu<=100):
  print("AA")

elif (sinavNotu>=70) and (sinavNotu<85):
  print("BB")

elif (sinavNotu>=55) and (sinavNotu<70):
  print("CC")

elif (sinavNotu>=45) and (sinavNotu<55):
  print("DD")

else :
  print("FF")

a=int (input("bir sayi giriniz:"))

if a==10:
  print(1)

  if a>0:
  print(2)
  else:
  print(3)
    if a>12:
    print(4)
    else:
    print(5)

else:
  print(6)
 #dışarıdan 10 girilirse kaç yazar

a=12

b=100 if a==10 else 50

print(b)

#önemli bu yapı çıktı olarak 50 yazar

durum=1

msg="başarılı" if durum==1 else "başarısız"

print(msg)

name="mete"

if name=='mete':
  print( " merhaba", name)



"""while

"""

i=1
while i<10:
  print(i)
  i+=1

print("hello\tWorld")

print("hello\nWorld")

print("merhaba",end=" ")
print("dünya")

print("merhaba",end="\n")
print("dünya")

print("merhaba",end="\t")
print("dünya")

print("merhaba",end="***")
print("dünya")

i=1
while i<10:
  print(i,end=" ")
  i+=1

i=1
while i<10:
  print(i**2,end=" ")
  i+=1

sekil="*"
sayi=1
while sayi<6:
  print(sekil)
  sekil+="*"
  sayi+=1
  #benim çözümüm

satır=1
n=5

while satır<=n:
  print("*"*satır)
  satır+=1
  #hocanın çözümü

satır=5
while satır>0:
  print("*"*satır)
  satır-=1

while True:
  print("lütfen adınızı yazınız:")
  name=input()

if name=="çıkış" or name=="ç" or name=="C":
  print("çıkış yapıldı")
  break

print("merhaba",name)



"""kullanıcının aldığı sayının faktöriyelini hesaplayan kod yazınız."""

sayi=int(input("lütfen sayı giriniz: "))
faktöriyel=1
while sayi>=1:
    faktöriyel*=sayi
    sayi-=1

print(faktöriyel)



"""#for

"""

for i in range(20): #20 ye kadar 20 ye eşit olmaz
  print(i)

for i in range(20,45,4):#20 den 45 ekadar 4 er artar
  print(i)

n=5
for i in range(1,n+1):
  print("*"*i)

n=5
for i in range(n,0,-1):
  print("*"*i)

for i in range(5):
  print("mete ({})".format(i))

for i in range(5):
  print("mete {}".format(i))

bulundu=0

for i in  [10,20,30,40]:
  if i==40:
    bulundu=1
    print("aranan eleman bulundu",i)
    break
  else:
    print("aranan eleman bulunamadı",i)

if bulundu==1:
  print("bulundu")
else:
  print("bulunamadı")

import random
for i in range(5):
  print(random.randint(1,100))

a,b=0,1

for i in range(10):
  print(a, end=' ')
  a,b=b,a+b

"""#2 ile 100 arasındaki asal sayıları bukan kodu oluşturun"""

for i in range(2,100):
  for t in range(2,i):
    if t%i==0 :
      break
  else:
    print(i)
#benim çözümüm

for sayı in range(2,100):
  asal=True
  for i in range(2,sayı):
    if(sayi%i==0):
      asal=False
      break
    if asal:
      print(sayı, end=" ")

    #hocanın çözümü