# -*- coding: utf-8 -*-
"""pythonProgramlamaDersi4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JY-b8AvL5XlExyzMFeAgUWdX6feg5hq8
"""

liste=[10,20,30,40]

liste.append(-999)

liste

len(liste)

liste[10]=-111 #yapayız ne listenin boyutunu aşabiliriz ne de bu şekilde ekleyebillriz.!!!!!

liste[4]=100

liste

liste.insert(2,543516)

liste

liste.insert(6,0)  #verilen indeksi ekler

liste.insert(100,-555) #ekler.kişinin aklında değilse kaçıncı indekste kaldığını büyük sayı yazıp listenin en sonuna ekler önemli bir nokta !!!!!!!!

"""#pop

"""

liste

liste.pop() #-555 gösterir ama son elemanı yani -555 i çıkarır.

liste.pop()

"""#indeks"""

liste

i=liste.index(20)
i

liste=[10,3.14,"erzurum",True]

i=liste.index("trabzon")
i                                    #hata verir false döndürmez unutma



"""#remove"""

liste

liste.remove(10)  #ilk gördüğü 10 u siler !



"""#count"""

liste=[10,10,22,33,4,5,66,77,10]

liste.count(10)

liste.count(-99)  #bu hta vermez 0 verir çünkü sayma işlemi yapıyor.

"""#sort"""

liste.sort()
liste

liste.sort(reverse=True)
liste

liste.clear()
liste

"""#copy

"""

liste=[77, 66, 33, 22, 10, 10, 10, 5, 4]

yeniListe=liste.copy()
yeniListe

yeniListe.pop()
yeniListe

"""başlangıçta boş olan bir liste tanımlayınız.Buliste 5 eleman kullanıcı yolıyla alınız.Listenin elemanlarının toplamını ve ortalamasını yazınız."""

liste=[]
toplam=0                                               #benim çözümüm
while len(liste)<5:
  print("Lütfen sayı giriniz:")
  sayı=int(input())
  liste.append(sayı)
  toplam+=sayı
  ortalama=toplam/len(liste)
print("toplam:",toplam)
print("Ortalama:",ortalama)
print(liste)

liste=[]

for i in range(5):
  eleman=int(input("lütfen {}. elemanı giriniz:".format(i+1)))   #hocanın ççözümü
  liste.append(eleman)
  toplam=toplam+eleman
  ortalama=toplam/len(liste)
print(toplam)
print(ortalama)
print(liste)



"""diğer çözümleride yaz
iki tane for
bir tane while döngüsü
"""

type(liste)

liste=["erzurum","trabzon",10,3.14,["ankara","istanbul"],14.53]

liste[4]

liste[4][1]  #[4][2] yazarsak hata verir.

liste1=["erzurum","ankara"]

liste2=[10,20,liste1]
liste2

liste2 [2][0]



liste2 [2][1]

liste1=[10,20,30]
liste2=[1,2,3]
liste3=liste1+liste2
liste3                                    #buradaki toplama işlemi string toplama işlemidir dikkatli ol

liste1=[10,20,30]
liste2=[1,2,3,4,5,6]
liste3=liste1+liste2
liste3

liste1=["erzrurum","ankara","trabzon"]
liste1.append("istanbul") # Use append() to add an element to the list
liste1

liste1=["erzrurum","ankara","trabzon"]
liste1 +="istanbul"
liste1

del liste[0]
liste

metin="merhaba"
type(metin)

liste4=list(metin)
type(liste4)

liste5=[i for i in range(10)]
liste5

x=[]

for i in range(10):
  x.append(i)

print(x)

arabalar=["bmw","mercedes","opel"]
modeller=["x6","e200","corsa"]

arabalar.append(modeller)  #liste gibi wkler listenin içine
arabalar

arabalar.extend(modeller)  #tek tek eleman şeklinde ekler listenin içine
arabalar

arabalar.reverse()
arabalar

