# -*- coding: utf-8 -*-
"""PythonProgramlamaDersi3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10zPlEylS0kXn6Th2RBVhHQCJ3a-Tbpm8
"""

liste=[10,20,30,-11]
liste

min(liste)

max(liste)

sum(liste)  #toplamı

for i in liste:
  print(i)

55 in liste #listenin içinde 55 olup olmadığını kontrol eder , olmadığında false

50 not in liste  #olmadığında True

for i in liste:
  print(i**2)

metin="Merhaba Dünya"

for i in metin:
  print(i)

liste=[10,11,True,"tugce",3.14,]

for i in liste:
  if i=="tugce":
    break
  print(i)



for i in liste:
  if i=="tugce":
    continue
  print(i)

for i in liste:
  if i=="tugce":
    pass   #buradada devam eder ama tugce yi yazdırır
  print(i)

sayı=int(input("Bir sayı Giriniz: "))

if sayı==0:
  pass    #bu şartı pas geç der ve girilen sayı 0 a eşit olduğunda hiçbir şey yapmaz.
elif sayı!=0:
  print("Merhaba Dünya")

i=10

while i<20:
  if i==13:
    continue            #!!!!
  print("i",i)
  i+=1

i=10

while i<20:
  if i==13:
    break
  print("i",i)
  i+=1

i=10

while i<20:
  if i==13:
    i+=1
    continue
  print("i",i)
  i+=1

i=10

while i<20:
  if i==13:
    pass
  print("i",i)      #yerlerini ve çıktıklarını bil
  i+=1

liste1=[1,2,3,]
liste2=[10,20,30]

a=10
for i in liste1:
  for j in liste2:
    if i>j:
      a=a+liste1[j]

a

liste=[10,20,30]
yeniListe=[]

for i in liste:
  yeniListe.append(i)

print(yeniListe)

yeniListe1=[i for i in liste]
print(yeniListe1)

meyveler=["muz","portakal","elma"]

meyveler.append("kavun")
print(meyveler)

meyveler.insert("muz")
print(meyveler)

meyveler.remove("muz")
print(meyveler)

meyveler.sort()
print(meyveler)

index=meyveler.index("muz")
print(index)

uzunluk=len(meyveler)
print(uzunluk)

meyveler.clear()
print(meyveler)

meyveler.reverse()
print(meyveler)

tersMeyveler=meyveler[::-1]
print(tersMeyveler)

tersMeyveler=meyveler[-3:]
print(tersMeyveler)

kopyalama=meyveler.copy()
print(kopyalama)

meyveler.extend(kopyalama)
print(meyveler)



"""sayılar=[1,2,3,4,5,6,7,8,9,10]
listesibdeki çift sayıları yeni bir listeye ekleyip yazdırın
"""

sayılar=[1,2,3,4,5,6,7,8,9,10]

çift_sayılar=[]

indeks=0

while indeks<len(sayılar):
  if sayılar[indeks]%2==0:
    çift_sayılar.append(sayılar[indeks])
  indeks+=1

print(çift_sayılar)

[2,-2,4,-10,2,33,-44]

"""[2,-2,4,-10,2,33,-44] verilen listedeki negatif sayıları 0 yap ve listeyi yazdır"""

liste=[2,-2,4,-10,2,33,-44]

indeks=0

while indeks<len(liste):
  if liste[indeks]<0:
    liste[indeks]=0
    indeks=indeks+1

print(liste)

"""elemanlar=["elma","muz","elma","muz","çilek","muz","portakal"] verilen listede tekara eden elemanları çıkartarak listeyi yazdırınız."""

elemanlar=["elma","muz","elma","muz","çilek","muz","portakal"]

indeks=0                                                       #benim çöz

while indeks< len(elemanlar):
  if count(elemanlar[indeks]>1):
      elemanlar.remove(elemanlar[indeks])
      indeks+=1

print(elemanlar)

elemanlar=["elma","muz","elma","muz","çilek","muz","portakal"]

yeniElemanlar=[]

for i in elemanlar:
  if i not in yeniElemanlar:
    yeniElemanlar.append(i)

print(yeniElemanlar)

elemanlar=["elma","muz","elma","muz","çilek","muz","portakal"]  #hocanın çözümü
yeniElemanlar=[]

for i in elemanlar:
  if i in yeniElemanlar:
    continue
  yeniElemanlar.append(i)

print(yeniElemanlar)