# -*- coding: utf-8 -*-
"""PythonProgramlamaDersi11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REhVCo6sHIOp4F8nNJFd-3saHFK7w3EY

#**Nesneye** **Yönelik**
"""

class Ogrenci:
  def yazdir(self):
    print("python class")

o=Ogrenci()

o.yazdir()

print(o)

print(Ogrenci)

class ogrenci1:
  def yazdır(self):
    print("merhaba")
    print(self)

o1=ogrenci1()
o1.yazdır()

print(o1)

class futbol:
  def gol(self,x):
    self.a=x
  def yazdır(self):
    print(self.a)


f=futbol()

f.gol(5)

f.a

a=10

id(a)

class Test:
  def ekle(self):
    print(self)
    print(id(self))
    print("eklenmedi")

t=Test()

print(t)

print(id(t))

t.ekle()

t2=Test()
print(t2)

t2.ekle()

class Test2:
  def ekle(self):
    print("bu bir metottur")
  def çıkartma(self,a,b):
    print(a-b)


t1=Test2()
t2=Test2()

t1.ekle()

t2.ekle()

t1.çıkartma(10,12)

t2.çıkartma(100,40)

class Test2:
  def yaz(self):
    print("bu bir fonkdiyondur")
  def degisken(self,a,b):
    self.x=a
    self.y=b
  def goster(self):
    print(self.x)
    print(self.y)

t1=Test2()
t2=Test2()

t1.yaz()

t2.yaz()

t1.degisken(100,-50)

t1.goster()

t1.x

class ogrenci:
  def __init__(self):
    print("bu bir yapıcı metottur")

o1=ogrenci()

class ogrenci2:
  def __init__(self,x):
    self.y=x

o2=ogrenci2(10)

o2.y

class ogrenci3:
  def __init__(self,a,b):
    self.a=a
    self.b=b

o3=ogrenci3(50,100)

o3.a

o3.b

class toplama():
  def __init__(self,a,b):
    self.x=a
    self.y=b
  def topla(self):
    print("toplam",self.x+self.y)

t1=toplama(10,20)
t1.topla()

class teacher:
  def __init__(self,name="mete"):
    self.name=name
  def goster(self):
    print(self.name,"benim en sevdiğim hocam")

t1=teacher()
t1.goster()

t2=teacher("ferhat")
t2.goster()

class Windows7:
  def yazdır(self):
    print("merhaba ben parent sınıf içerisindeyim")

class Windows10(Windows7):
  def goster(self):
    print("merhaba ben child sınıf içerisindeyim")

x=Windows10()
x.yazdır()

y=Windows7()
y.yazdır()