# -*- coding: utf-8 -*-
"""pythonProgramlamaDersi5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vhVHJM4C6G_xs_tXXuRHOsizQBJcpCdT
"""



"""#Tuple

"""

tuple1=("mete",25,"erzurum")

tuple2="mete",40,3.14

tuple3=(25,) #bu tuple a veri eklenecek demektir.

tuple1[0]

del tuple2 #silme işlemi tamamıyla bellekten siler.

for i in tuple1:
  print(i)

if "mete" in tuple1:
  print("mete tuple1 in içinde var")
else:
  print("mete tuple1 in içinde yok")

tuple5=("M","e","r","h","a","b","a")

len(tuple5)

tuple5.count("a")

tuple5.index("M")

tuple6=("a","b")*5
tuple6

tuple7=(1,2,3)+(4,5,6)
tuple7

tuple8=list(tuple7)
type(tuple8)
tuple8

a=(1,2,3,4,5,6,7,8,9,10)
a[1:5]

a[1:]

a[:5]

a[::2]

a[::-1]

ad,yaş,sehir=tuple1
ad
yaş
sehir

ad

yaş

tuple2=(0,1,2,3,4,5)
tuple2

ilkEleman,*ortaElemanlar,sonEleman=tuple2 #ortaelemanı listeye dönüştüürür yıldızlı olanı  #çok öneli yapı



ilkEleman

ortaElemanlar

sonEleman

ortaElemanlar=tuple(ortaElemanlar)
ortaElemanlar

a=((0,1,2),(3,4,5),(6,7,8))

a[1][2]

import sys
liste=[1,2,3,4,5,"merhaba",3.14,True]
tuple9=(1,2,3,4,5,"merhaba",3.14,True)
print("liste boyutu:",sys.getsizeof(liste),"byte")
print("tuple boyutu:",sys.getsizeof(tuple9),"byte")

import timeit
print(timeit.timeit(stmt='[1,2,3,4,5,'merhaba',3.14,True]'))
print(timeit.timeit(stmt='(1,2,3,4,5,'merhaba',3.14,True)'))



"""#sözlük

"""

sözlük={"isim":"mete","yaş":25,"şehir":"erzurum"}
sözlük

sözlük["isim"]

sözlük["meslek"]="akademisyen"  #ekleme yaparken



sözlük

del sözlük["meslek"]

sözlük

sözlük.pop("yaş") #anahatarı verilen değer silinir

sözlük

sözlük.popitem()  #son eleman silimnir

sözlük

sözlük.clear()

sözlük

sözlük={"isim":"mete","yaş":25,"şehir":"erzurum"}
sözlük

if "isim" in sözlük:
  print(sözlük["isim"])

for i in sözlük:
  print(i,sözlük[i])

sözlük.keys()

for i in sözlük.keys():
  print(i)

sözlük.values()

for i in sözlük.values():
  print(i)

sözlük.items()

for anahtar,değer in sözlük.items():
  print(anahtar,değer)

sözlük["isim"]="ferhat"

sözlük

a=dict(sözlük)
type(a)

sözlük2=dict(isim="mete",yaş=40,şehir="trabzon")

sözlük.update(sözlük2)
sözlük

import pandas as pd

sözlük ={
    "isim":["mete","ahmet","ferhat","batu"],
    "yas":[25,30,35,45],
    "sehir":["erzurum","trabson","ankara","bursa"]
}

df=pd.DataFrame(sözlük)
print(df)

df["maaş"]=None

df

df.at[1,"maaş"]=50000
df.at[3,"maaş"]=10000
df

kisiler={
    "mete":["basketbol","yüzme"],
    "batu":["yüeüşü","sinema","kitap okuma"],
    "ebru":["yüzme"],
    "ferhat":["yüzme","futbol","basketbol","dağcılık"]
}

for i in kisiler:
  print(kisiler.keys(i),count(kisiler.values(i)))


for i in kisiler:
  print(kisiler.keys(i))

kisiler={
    "mete":["basketbol","yüzme"],
    "batu":["yüeüşü","sinema","kitap okuma"],
    "ebru":["yüzme"],
    "ferhat":["yüzme","futbol","basketbol","dağcılık"]
}

hobi_sayıları={kisi:len(hobiler)for kisi,hobiler in kisiler.items()}            #hocanın çözümü
print(hobi_sayıları)

