# -*- coding: utf-8 -*-
"""PythonProgramlamaDersi13Database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYIjWWma5ZvGbupDwC05lS6GzxUfIy55
"""

import sqlite3

conn=sqlite3.connect("/content/ogrenci.db")

conn.execute("""CREATE TABLE ogrenci_detay4
    (ID INT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    AGE INT,
    ADRESS BLOB,
    BURS REAL);
    """)

conn.close()

conn=sqlite3.connect("/content/ogrenci.db")

conn.execute("Insert into ogrenci_detay4 values(900,'Mete',40,'Istanbul',1000.00)");
conn.execute("Insert into ogrenci_detay4 values(901,'ferhat',50,'trabzon',3000.00)");
conn.execute("Insert into ogrenci_detay4 values(902,'batu',45,'erzurum',2000.00)");
conn.commit()

data=conn.execute("Select * from ogrenci_detay2")
for i in data:
    print("ID",i[0])
    print("ISIM",i[1])
    print("YAS",i[2])
    print("ADRES",i[3])
    print("MAAS",i[4], "\n")

conn.execute("Insert into ogrenci_detay2 values(903,"buket",25,"trabzon",3000.00)");

data=conn.execute("Select * from ogrenci_detay2")
for i in data:
    print("ID",i[0])
    print("ISIM",i[1])
    print("YAS",i[2])
    print("ADRES",i[3])
    print("MAAS",i[4], "\n")

conn.execute("UPDATE ogrenci_detay2 SET BURS =4000.00 WHERE ID=903" )
conn.commit()

data=conn.execute("Select * from ogrenci_detay2")
for i in data:
    print("ID",i[0])
    print("ISIM",i[1])
    print("YAS",i[2])
    print("ADRES",i[3])
    print("MAAS",i[4], "\n")

conn.total_changes

conn.execute("UPDATE ogrenci_detay2 SET BURS =1000.00 WHERE ID=903" )
conn.commit()

conn.total_changes

conn.execute("DELETE FROM ogrenci_detay2 WHERE ID=903" )
conn.commit()

conn.total_changes

data=conn.execute("Select * from ogrenci_detay2")
for i in data:
    print("ID",i[0])
    print("ISIM",i[1])
    print("YAS",i[2])
    print("ADRES",i[3])
    print("MAAS",i[4], "\n")

conn.close()

